const menu = [
  {
    id: 1,
    title: 'Süzme Pankek',
    category: 'breakfast',
    price: 85.99,
    img: './images/item-1.jpeg',
    desc: 'Sütün lezzeti buttermilk pankeklerde! Yumuşacık bir dokuya sahip süzme pankeklerimizle gününüze tat katın.',
  },
  {
    id: 2,
    title: 'Diner ikili hamburger',
    category: 'lunch',
    price: 153.99,
    img: './images/item-2.jpeg',
    desc: 'Diner usulü hazırlanan ikili hamburgerimiz, enfes lezzeti ve doyurucu yapısıyla lunchniz için mükemmel bir tercih!',
  },
  {
    id: 3,
    title: 'Godzilla milkshake',
    category: 'shakes',
    price: 36.99,
    img: './images/item-3.jpeg',
    desc: 'Efsanevi bir lezzet sizi bekliyor! Godzilla Milkshake imizle kendinizi şımartın ve tatlı bir mola verin.',
  },
  {
    id: 4,
    title: 'Köy lezzeti',
    category: 'breakfast',
    price: 60.99,
    img: './images/item-4.jpeg',
    desc: 'Köy breakfastlarının vazgeçilmez lezzeti artık burada! Tamamen doğal malzemelerle hazırlanan Köy Lezzeti breakfastsı, sizleri enfes bir lezzet şölenine davet ediyor.',
  },
  {
    id: 5,
    title: 'Yumurta saldırısı',
    category: 'lunch',
    price: 92.99,
    img: './images/item-5.jpeg',
    desc: 'Köy breakfastlarının vazgeçilmez lezzeti artık burada! Tamamen doğal malzemelerle hazırlanan Köy Lezzeti breakfastsı, sizleri enfes bir lezzet şölenine davet ediyor.',
  },
  {
    id: 6,
    title: 'Oreo Hayali',
    category: 'shakes',
    price: 58.99,
    img: './images/item-6.jpeg',
    desc: 'Oreo sevenler için muhteşem bir lezzet! Oreo Hayali sizi tatlı bir dünyaya götürüyor. Lezzetine doyum olmaz!',
  },
  {
    id: 7,
    title: 'Bacon Seli',
    category: 'breakfast',
    price: 28.99,
    img: './images/item-7.jpeg',
    desc: 'breakfastnın olmazsa olmazı bacon sevenleri için! Bol bol taze kızarmış bacon ve diğer lezzetlerle hazırlanan Bacon Seli, güne harika bir başlangıç yapmanızı sağlayacak.',
  },
  {
    id: 8,
    title: 'Amerikan Klasik',
    category: 'lunch',
    price: 222.99,
    img: './images/item-8.jpeg',
    desc: 'Amerikan mutfağının klasik lezzetleriyle hazırlanan bu lunch, tadına doyum olmayan bir deneyim sunuyor. Üstelik uygun fiyatıyla da tercih sebebi!',
  },
  {
    id: 9,
    title: 'Karantina Arkadaşı',
    category: 'shakes',
    price: 26.99,
    img: './images/item-9.jpeg',
    desc: 'Karantina günlerinde canınızın sıkıldığı anlarda sizi yalnız bırakmayacak lezzetli bir milkshake! Karantina Arkadaşı ile tatlı bir kaçamak yapın.',
  },
  {
    id: 10,
    title: 'Bizon Bifteği',
    category: 'lunch',
    price: 322.99,
    img: './images/item-10.jpeg',
    desc: 'Bizon etinin eşsiz lezzeti, özel baharatlar ve soslarla birleşiyor. Bizon Bifteği, akşam yemeğiniz için mükemmel bir seçim!',
  },
  {
    id: 11,
    title: 'Meksika Tacos',
    category: 'lunch',
    price: 94.99,
    img: './images/item-11.jpeg',
    desc: 'Meksika mutfağının eşsiz lezzetiyle hazırlanan enfes taco çeşitleri. Baharatlı ve doyurucu bir lezzet deneyimi!',
  },
  {
    id: 12,
    title: 'Çıtır Çıtır Patates Kızartması',
    category: 'sides',
    price: 25.99,
    img: './images/item-12.jpeg',
    desc: 'Altın sarısı renginde, çıtır çıtır dışı ve yumuşacık içiyle lezzetli patates kızartmaları. İsteğe bağlı soslarla servis edilir.',
  },
  {
    id: 13,
    title: 'Mango Delight Smoothie',
    category: 'shakes',
    price: 29.99,
    img: './images/item-13.jpeg',
    desc: 'Mango, muz ve vanilya dondurma ile hazırlanan ferahlatıcı bir smoothie. Yazın sıcak günlerinde serinlemek için ideal!',
  },

  {
    id: 14,
    title: 'Vejetaryen Ziyafet',
    category: 'dinner',
    price: 117.99,
    img: './images/item-14.jpeg',
    desc: 'Sağlıklı ve lezzetli sebzelerle hazırlanan vejetaryen bir ziyafet. Protein açısından zengin, doyurucu bir seçenek!',
  },
  {
    id: 15,
    title: 'Çikolatalı Brownie',
    category: 'dessert',
    price: 38.99,
    img: './images/item-15.jpeg',
    desc: 'Yoğun çikolata aromalı, içi yumuşacık ve dışı çıtır çıtır brownie tatlısı. Tatlı krizlerinize şahane bir çözüm!',
  },
];

export default menu;
